# syntax=docker/dockerfile:1.7

ARG NGINX_RUNTIME_IMAGE="{{nginx_runtime_image}}"

FROM ${NGINX_RUNTIME_IMAGE} AS runtime
WORKDIR {{nginx_html_dir}}

COPY {{nginx_config_path}} /etc/nginx/conf.d/default.conf
COPY {{static_assets_dir}} {{nginx_html_dir}}

EXPOSE {{privileged_listen_port}}
HEALTHCHECK --interval={{healthcheck_interval}} --timeout={{healthcheck_timeout}} --start-period={{healthcheck_start_period}} --retries={{healthcheck_retries}} \
    CMD {{nginx_healthcheck_command}}

CMD ["nginx", "-g", "daemon off;"]
