# syntax=docker/dockerfile:1.7

ARG NODE_BUILD_IMAGE="{{node_build_image}}"
ARG NGINX_RUNTIME_IMAGE="{{nginx_runtime_image}}"

FROM ${NODE_BUILD_IMAGE} AS deps
WORKDIR {{frontend_workdir}}

ENV NODE_ENV=development
COPY {{package_manager_files}} ./
RUN --mount=type=cache,target={{package_manager_cache_target}} \
    {{package_manager_install_command}}

FROM deps AS build
ARG VITE_PUBLIC_BASE_URL="{{vite_public_base_url}}"
ARG VITE_API_BASE_URL="{{vite_api_base_url}}"
ENV NODE_ENV=production \
    VITE_PUBLIC_BASE_URL="${VITE_PUBLIC_BASE_URL}" \
    VITE_API_BASE_URL="${VITE_API_BASE_URL}"

COPY {{frontend_source_paths}} ./
RUN {{frontend_build_command}}

FROM ${NGINX_RUNTIME_IMAGE} AS runtime
COPY {{nginx_config_path}} /etc/nginx/conf.d/default.conf
COPY --from=build {{frontend_dist_dir}} {{nginx_html_dir}}

EXPOSE {{nginx_listen_port}}
HEALTHCHECK --interval={{healthcheck_interval}} --timeout={{healthcheck_timeout}} --start-period={{healthcheck_start_period}} --retries={{healthcheck_retries}} \
    CMD {{nginx_healthcheck_command}}

CMD ["nginx", "-g", "daemon off;"]
